# 关于引号的使用 一般如果变量不是在口头位置 不适用引号

[root@ansible data]# cat yinhao.yaml 
---
- hosts: pro1
  vars:
    data_dir: /data
  remote_user: root
  tasks:
    - name: 引号使用测试
      shell: cd {{data_dir}};ls

[root@ansible data]# ansible-playbook yinhao.yaml --verbose
Using /etc/ansible/ansible.cfg as config file

PLAY [pro1] ***********************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [192.168.29.250]

TASK [引号使用测试] *********************************************************************************************************************************************************************************
changed: [192.168.29.250] => {"changed": true, "cmd": "cd /data;ls", "delta": "0:00:00.004936", "end": "2018-06-26 09:49:14.427360", "rc": 0, "start": "2018-06-26 09:49:14.422424", "stderr": "", "stderr_lines": [], "stdout": "ansible-study\napache-tomcat-8.0.45\nbackup\nhua1\nhua2\nhua3\nhuahua1\nhuahua.tar.gz\njdk-8u91-linux-x64.rpm\njenkins-2.121.1-1.1.noarch.rpm\nmftp.yml\npasswd\ntest2018\ntest.gz", "stdout_lines": ["ansible-study", "apache-tomcat-8.0.45", "backup", "hua1", "hua2", "hua3", "huahua1", "huahua.tar.gz", "jdk-8u91-linux-x64.rpm", "jenkins-2.121.1-1.1.noarch.rpm", "mftp.yml", "passwd", "test2018", "test.gz"]}

PLAY RECAP ************************************************************************************************************************************************************************************
192.168.29.250             : ok=2    changed=1    unreachable=0    failed=0   

# 添加引号后

[root@ansible data]# ansible-playbook yinhao.yaml --verbose
Using /etc/ansible/ansible.cfg as config file

PLAY [pro1] ***********************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [192.168.29.250]

TASK [引号使用测试] *********************************************************************************************************************************************************************************
changed: [192.168.29.250] => {"changed": true, "cmd": "cd data_dir;ls", "delta": "0:00:00.004589", "end": "2018-06-26 09:47:17.881180", "rc": 0, "start": "2018-06-26 09:47:17.876591", "stderr": "/bin/sh: line 0: cd: data_dir: No such file or directory", "stderr_lines": ["/bin/sh: line 0: cd: data_dir: No such file or directory"], "stdout": "anaconda-ks.cfg\napache-tomcat-8.0.45\n~None", "stdout_lines": ["anaconda-ks.cfg", "apache-tomcat-8.0.45", "~None"]}

PLAY RECAP ************************************************************************************************************************************************************************************
192.168.29.250             : ok=2    changed=1    unreachable=0    failed=0   
